- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC variables
      include_vars: vars/vpc_setup
     
    - name: Create VPC
      ec2_vpc_net:
          name: "{{vpc_name}}"
          cidr_block: "{{vpcCidr}}"
          region: "{{region}}"
          dns_support: yes
          dns_hostnames: yes
          tenancy: default
          state: "{{state}}"
      register: vpc_details

    - debug:
       var: vpc_details

    - name: Public Subnet 1
      amazon.aws.ec2_vpc_subnet: 
         state: "{{state}}"
         vpc_id: "{{vpc_details.vpc.id}}"
         region: "{{region}}"
         az: "{{zone1}}"
         map_public: true
         cidr: "{{PubSubCidr1}}"
         tags:
          Name: Public subnet us-east-1a
      register: pub_sub1_out
    
    - name: Private Subnet 1
      amazon.aws.ec2_vpc_subnet: 
         state: "{{state}}"
         vpc_id: "{{vpc_details.vpc.id}}"
         region: "{{region}}"
         az: "{{zone2}}"
         cidr: "{{PrivSubCidr1}}"
         tags:
          Name: Private subnet us-east-1a
      register: priv_sub1_out

    - name: Internet Gateway Code
      amazon.aws.ec2_vpc_igw_info:
        region: "{{region}}"
        vpc_id: "{{vpc_details.vpc.id}}"
        profile: Test
        tags:
          Name: IGW for Public Subnet  
      register: igw_out
      