- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC variables
      include_vars: vars/vpc_setup
     
    - name: Create VPC
      ec2_vpc_net:
          name: "{{vpc_name}}"
          cidr_block: "{{vpcCidr}}"
          region: "{{region}}"
          dns_support: yes
          dns_hostnames: yes
          tenancy: default
          state: "{{state}}"
      register: vpc_details

    - debug:
       var: vpc_details

    - name: Public Subnet 1
      amazon.aws.ec2_vpc_subnet: 
         state: "{{state}}"
         vpc_id: "{{vpc_details.vpc.id}}"
         region: "{{region}}"
         az: "{{zone1}}"
         map_public: true
         cidr_block: "{{PubSubCidr1}}"
         tags:
          Name: Public subnet us-east-1a
      register: pub_sub1_out