- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC variables
      include_vars: vars/vpc_setup
     
    - name: Create VPC
      ec2_vpc_net:
          name: "{{vpc_name}}"
          cidr_block: "{{vpcCidr}}"
          region: "{{region}}"
          dns_support: yes
          dns_hostnames: yes
          tenancy: default
          state: "{{state}}"
      register: vpc_details

    - debug:
       var: vpc_details

    - name: Public Subnet 1
      amazon.aws.ec2_vpc_subnet: 
         state: "{{state}}"
         vpc_id: "{{vpc_details.vpc.id}}"
         region: "{{region}}"
         az: "{{zone1}}"
         map_public: true
         cidr: "{{PubSubCidr1}}"
         tags:
          Name: Public subnet us-east-1a
      register: pub_sub1_out
    
    - name: Private Subnet 1
      amazon.aws.ec2_vpc_subnet: 
         state: "{{state}}"
         vpc_id: "{{vpc_details.vpc.id}}"
         region: "{{region}}"
         az: "{{zone2}}"
         cidr: "{{PrivSubCidr1}}"
         tags:
          Name: Private subnet us-east-1a
      register: priv_sub1_out

    - name: Internet Gateway Code
      amazon.aws.ec2_vpc_igw:
        region: "{{region}}"
        vpc_id: "{{vpc_details.vpc.id}}"
        tags:
          Name: IGW for Public Subnet  
      register: igw_out
      
    - name: Create Route Table for Public Subnet.
      amazon.aws.ec2_vpc_route_table:
        region: "{{region}}"
        vpc_id: "{{vpc_details.vpc.id}}"
        subnets:
          - "{{pub_sub1_out.subnet.id}}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{igw_out.gateway_id}}"
        tags:
          Name: RT for Pub Subnet
      register: rt_pub_out

    - name: Create NAT Gateway in Pub Subnet.
      amazon.aws.ec2_vpc_nat_gateway:
        state: "{{state}}"
        region: "{{region}}"
        subnet_id: "{{pub_sub1_out.subnet.id}}"
        if_exist_do_not_create: true
        wait: yes
      register: nat_gw_out
    
    - name: Create Route Table for Private Subnet.
      amazon.aws.ec2_vpc_route_table:
        region: "{{region}}"
        vpc_id: "{{vpc_details.vpc.id}}"
        subnets:
          - "{{priv_sub1_out.subnet.id}}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{nat_gw_out.nat_gateway_id}}"
        tags:
          Name: RT for Priv Subnet
      register: rt_priv_out

    - debug:
       var: "{{item}}"
      loop:
        - vpc_details.vpc.id
        - pub_sub1_out.subnet.id
        - priv_sub1_out.subnet.id
        - igw_out.gateway_id
        - rt_priv_out.route_table.id
        - nat_gw_out.nat_gateway_id
        - rt_pub_out.route_table.id
    
    - name: Creating variable files for all VPC component outputs
      copy:
        content: "{{vpc_details.vpc.id}}\n{{pub_sub1_out.subnet.id}}\n{{priv_sub1_out.subnet.id}}\n{{igw_out.gateway_id}}\n{{rt_priv_out.route_table.id}}\n{{nat_gw_out.nat_gateway_id}}\n{{rt_pub_out.route_table.id}}"
        dest: vars/vpc_comp_ids